# Generated by Django 3.1.7 on 2021-05-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('puesto', models.CharField(max_length=200, verbose_name='Puesto')),
                ('telefono', models.CharField(max_length=200, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('usuario', models.CharField(max_length=200, verbose_name='Usuario')),
                ('contraseña', models.CharField(max_length=200, verbose_name='Contraseña')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=250, verbose_name='Producto')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('preciocompra', models.FloatField(verbose_name='Precio de compra')),
                ('precioventa', models.FloatField(verbose_name='Precio de venta')),
                ('existencia', models.IntegerField(verbose_name='Existencia')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['producto'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(verbose_name='Total')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nit', models.CharField(max_length=250, verbose_name='Nit')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('empleados_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia2.empleados')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Infoventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('productos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia2.productos')),
                ('ventas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia2.ventas')),
            ],
            options={
                'verbose_name': 'Infoventa',
                'verbose_name_plural': 'Infoventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('productos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia2.productos')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
    ]
